# Generated by Django 2.1.7 on 2019-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20190402_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='weathers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wCity', models.CharField(max_length=16)),
                ('wDate', models.CharField(max_length=16)),
                ('wWeather', models.CharField(max_length=64)),
                ('wTemp', models.CharField(max_length=32)),
            ],
        ),
    ]
