# Generated by Django 2.1.7 on 2019-04-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='shubao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=32)),
                ('n', models.CharField(max_length=1000)),
            ],
        ),
    ]
