# Generated by Django 2.1.7 on 2019-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_shubao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shubao',
            old_name='p',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='shubao',
            name='n',
        ),
        migrations.AddField(
            model_name='shubao',
            name='Title',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
